version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    # depends_on:
    #   - db
    ports:
      - "${WEB_PORT:-8000}:8000"
    volumes:
      - ./client:/usr/src/app/client
      - ./config:/usr/src/app/config
      - ./server:/usr/src/app/server
      # - ./.babelrc:/usr/src/app/.babelrc
      - ./.eslintrc.json:/usr/src/app/.eslintrc.json
      - ./server.js:/usr/src/app/server.js
      - ./package.json:/usr/src/app/package.json
      # - ./package-lock.json:/usr/src/app/package-lock.json
      - ./webpack.config.js:/usr/src/app/webpack.config.js
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm run lint
  # db:
  #   image: mongo:latest
  #   volumes:
  #     - dbdata:/data/db
volumes:
  dbdata:
